version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ service
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  submission-service:
    build:
      context: .
      dockerfile: cmd/submission-service/Dockerfile
    container_name: submission-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  execution-service:
    build:
      context: .
      dockerfile: cmd/execution-service/Dockerfile
    container_name: execution-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq

  notification-service:
    build:
      context: .
      dockerfile: cmd/notification-service/Dockerfile
    container_name: notification-service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - WEBSOCKET_SERVICE_URL=http://websocket-service:8000/send
    depends_on:
      - rabbitmq
      - websocket-service

  websocket-service:
    build:
      context: .
      dockerfile: cmd/websocket-service/Dockerfile
    container_name: websocket-service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
