apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-service
  labels:
    app: submission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submission-service
  template:
    metadata:
      labels:
        app: submission-service
    spec:
      containers:
      - name: submission-service
        image: submission-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: submission-service
  labels:
    app: submission-service
spec:
  selector:
    app: submission-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP